#!/usr/bin/env bash
#
# start-mysql.sh
# ==============
# Starts an ephemeral MySQL container for testing the SQLAlchemy Core demo.
#
# A random root password is generated each run and the full DATABASE_URL is
# written to a gitignored .demo-mysql.env file alongside this script. The
# user sources that file to pick up the credential, mimicking the real-world
# pattern where passwords live in env vars or config files outside source.
#
# The container:
#   - is named 'python-db-mysql'
#   - runs mysql:8.4 (current LTS as of April 2024)
#   - listens on host port 3306 (localhost only)
#   - auto-creates a database called 'demo'
#   - is removed automatically when stopped (--rm)
#
# First-run startup takes 15 to 30 seconds while MySQL initialises its data
# directory. Subsequent starts after a stop are equally slow because --rm
# discards the volume.
#
# Usage:
#   ./start-mysql.sh
#   source .demo-mysql.env
#   python sqlalchemy_demo.py --backend mysql
#
# Requires: docker, openssl

set -euo pipefail

CONTAINER_NAME="python-db-mysql"
IMAGE="mysql:8.4"
HOST_PORT=3306
DB_NAME="demo"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.demo-mysql.env"

if ! docker info > /dev/null 2>&1; then
    echo "Error: Docker daemon is not running. Start Docker Desktop and try again."
    exit 1
fi

if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    echo "Container '${CONTAINER_NAME}' is already running."
    if [[ -f "${ENV_FILE}" ]]; then
        echo "Existing credentials are in ${ENV_FILE}."
    else
        echo "Warning: no env file found at ${ENV_FILE} — stop and restart to regenerate."
    fi
    exit 0
fi

DB_PASSWORD="$(openssl rand -hex 16)"

echo "Starting ${IMAGE} as '${CONTAINER_NAME}' on port ${HOST_PORT}…"
docker run --rm -d \
    --name "${CONTAINER_NAME}" \
    -e MYSQL_ROOT_PASSWORD="${DB_PASSWORD}" \
    -e MYSQL_DATABASE="${DB_NAME}" \
    -p "${HOST_PORT}:3306" \
    "${IMAGE}" > /dev/null

echo -n "Waiting for MySQL to accept connections (this can take 15–30 seconds on first run)"
until docker exec "${CONTAINER_NAME}" mysqladmin ping -uroot -p"${DB_PASSWORD}" --silent > /dev/null 2>&1; do
    echo -n "."
    sleep 2
done
echo " ready."

(umask 077 && cat > "${ENV_FILE}" <<EOF
# Generated by start-mysql.sh — do not commit.
export DATABASE_URL="mysql+pymysql://root:${DB_PASSWORD}@localhost:${HOST_PORT}/${DB_NAME}"
EOF
)

echo
echo "Credentials written to ${ENV_FILE} (permissions 0600)."
echo
echo "To run the demo against this database:"
echo
echo "  source $(basename "${ENV_FILE}")"
echo "  python sqlalchemy_demo.py --backend mysql"
echo
echo "When finished, stop and remove the container with:"
echo
echo "  ./stop-mysql.sh"
