#!/usr/bin/env bash
#
# start-postgres.sh
# =================
# Starts an ephemeral PostgreSQL container for testing the SQLAlchemy Core demo.
#
# A random password is generated each run and the full DATABASE_URL is written
# to a gitignored .demo-postgres.env file alongside this script. The user
# sources that file to pick up the credential — closer to real-world usage,
# where passwords live in env vars or config files outside source.
#
# The container:
#   - is named 'python-db-postgres'
#   - runs postgres:16
#   - listens on host port 5432 (localhost only)
#   - is removed automatically when stopped (--rm)
#
# Usage:
#   ./start-postgres.sh
#   source .demo-postgres.env
#   python sqlalchemy_demo.py --backend postgres
#
# Requires: docker, openssl

set -euo pipefail

CONTAINER_NAME="python-db-postgres"
IMAGE="postgres:16"
HOST_PORT=5432
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.demo-postgres.env"

if ! docker info > /dev/null 2>&1; then
    echo "Error: Docker daemon is not running. Start Docker Desktop and try again."
    exit 1
fi

if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
    echo "Container '${CONTAINER_NAME}' is already running."
    if [[ -f "${ENV_FILE}" ]]; then
        echo "Existing credentials are in ${ENV_FILE}."
    else
        echo "Warning: no env file found at ${ENV_FILE} — stop and restart to regenerate."
    fi
    exit 0
fi

DB_PASSWORD="$(openssl rand -hex 16)"

echo "Starting ${IMAGE} as '${CONTAINER_NAME}' on port ${HOST_PORT}…"
docker run --rm -d \
    --name "${CONTAINER_NAME}" \
    -e POSTGRES_PASSWORD="${DB_PASSWORD}" \
    -p "${HOST_PORT}:5432" \
    "${IMAGE}" > /dev/null

echo -n "Waiting for Postgres to accept connections"
until docker exec "${CONTAINER_NAME}" pg_isready -U postgres > /dev/null 2>&1; do
    echo -n "."
    sleep 1
done
echo " ready."

(umask 077 && cat > "${ENV_FILE}" <<EOF
# Generated by start-postgres.sh — do not commit.
export DATABASE_URL="postgresql+psycopg2://postgres:${DB_PASSWORD}@localhost:${HOST_PORT}/postgres"
EOF
)

echo
echo "Credentials written to ${ENV_FILE} (permissions 0600)."
echo
echo "To run the demo against this database:"
echo
echo "  source $(basename "${ENV_FILE}")"
echo "  python sqlalchemy_demo.py --backend postgres"
echo
echo "When finished, stop and remove the container with:"
echo
echo "  ./stop-postgres.sh"
